Project-LTW/Project-LTW/Models/DiaDanh.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project_LTW.Models
{
    public class DiaDanh
    {
        public int ID { set; get; }
        //Tieu De
        [Required(ErrorMessage = "Dữ liệu chưa được nhập")]
        [StringLength(500, ErrorMessage = "Số lượng ký tự từ 20-500", MinimumLength = 2)]
        public String Title { set; get; }

        //Noi Dung
        [Required(ErrorMessage = "Dữ liệu chưa được nhập")]
        [StringLength(5000, ErrorMessage = "Số lượng ký tự từ 20-5000", MinimumLength = 2)]
        public String Body { set; get; }

        //Ngay dang
        [Required(ErrorMessage = "Dữ liệu chưa được nhập")]
        [DataType(DataType.DateTime)]
        public DateTime DateCreate { set; get; }

        //1 bài viết của 1 người dùng
        public virtual UserProfile UserProfile { set; get; }
        public int UserProfileID { set; get; }
        // 1 bài viết có nhiều Comment
        public virtual ICollection<Comment> Comments { set; get; }
        public virtual ICollection<Rating> Ratings { set; get; }
        //1 bài viết có nhiều tag
        public virtual ICollection<Tag> Tags { set; get; }
    }
}

Project-LTW/Project-LTW/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project_LTW.Models;

namespace Project_LTW.Controllers
{
    public class CommentController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.DiaDanhs).Include(c => c.TrungTams);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.DiaDanhID = new SelectList(db.DiaDanhs, "ID", "Title");
            ViewBag.TrungTamID = new SelectList(db.TrungTam, "ID", "Title");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment,int idtrungtam,int iddiadanh,int loai)
        {
            if (ModelState.IsValid)
            {
                comment.Loai = loai;
                comment.TrungTamID = idtrungtam;
                comment.DiaDanhID = iddiadanh;
                comment.DateCreated = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return PartialView("viewComment", comment);
            }

            ViewBag.DiaDanhID = new SelectList(db.DiaDanhs, "ID", "Title", comment.DiaDanhID);
            ViewBag.TrungTamID = new SelectList(db.TrungTam, "ID", "Title", comment.TrungTamID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.DiaDanhID = new SelectList(db.DiaDanhs, "ID", "Title", comment.DiaDanhID);
            ViewBag.TrungTamID = new SelectList(db.TrungTam, "ID", "Title", comment.TrungTamID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DiaDanhID = new SelectList(db.DiaDanhs, "ID", "Title", comment.DiaDanhID);
            ViewBag.TrungTamID = new SelectList(db.TrungTam, "ID", "Title", comment.TrungTamID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project-LTW/Project-LTW/Controllers/DiaDanhController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project_LTW.Models;

namespace Project_LTW.Controllers
{
    [Authorize]
    public class DiaDanhController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /DiaDanh/
        [AllowAnonymous]
        public ActionResult Index(string Publishers, string strSearch)
        {
            var diadanhs = db.DiaDanhs.Include(p => p.UserProfile);
            //return View(posts.ToList());
            //Select all Book records
            var diadanh = from b in db.DiaDanhs

                       select b;

            //Get list of Book publisher
            var publisherList = from c in diadanh
                                orderby c.Title
                                select c.Title;

            //Set distinct list of publishers in ViewBag property
            //ViewBag.Publishers = new SelectList(publisherList.Distinct());

            //Search records by Book Name 
            if (!string.IsNullOrEmpty(strSearch))
                diadanh = diadanh.Where(m => m.Title.Contains(strSearch));
            return View(diadanh);
            //return View(db.DiaDanhs.ToList());
        }

        //
        // GET: /DiaDanh/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            DiaDanh diadanh = db.DiaDanhs.Find(id);
            if (diadanh == null)
            {
                return HttpNotFound();
            }
            ViewData["idtrungtam"] = 1;
            ViewData["iddiadanh"] = id;
            ViewData["Loai"] = 1;
            return View(diadanh);
        }

        //
        // GET: /DiaDanh/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /DiaDanh/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(DiaDanh diadanh,string Content)
        {
            if (ModelState.IsValid)
            {
                //var ds = from n in db.Ratings
                //         where n.DiaDanhID == diadanh.ID
                //      group n by n.DiaDanhID into g
                //         select new { TB = g.Average(x => x.Diem) };
                //diadanh.DanhGiaDD = db.Ratings.Select
                diadanh.DateCreate = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).Where(y => y.UserName == User.Identity.Name).Single().UserId;
                diadanh.UserProfileID = userid;
                //Tao list các tag
                List<Tag> Tags = new List<Tag>();
                //tach cac Tag theo dau ,
                string[] TagContent = Content.Split(',');
                //Lập các tag vừa tách
                foreach (string item in TagContent)
                {
                    //Tìm xem tag content đã có hay chưa
                    Tag TagExists = null;
                    var ListTag = db.Tag.Where(y => y.Content.Equals(item.Trim()));
                    if (ListTag.Count() > 0)
                    {
                        //nếu có tag rồi thì add thêm Post vào
                        TagExists = ListTag.First();
                        TagExists.DiaDanhs.Add(diadanh);
                    }
                    else
                    {
                        //nếu chưa có tag thì tạo mới
                        TagExists = new Tag();
                        TagExists.Content = item.Trim();
                        TagExists.DiaDanhs = new List<DiaDanh>();
                        TagExists.DiaDanhs.Add(diadanh);
                    }
                    //add vào List các tag
                    Tags.Add(TagExists);
                }
                //Gán List Tag cho Post
                diadanh.Tags = Tags;
                db.DiaDanhs.Add(diadanh);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(diadanh);
        }

        //
        // GET: /DiaDanh/Edit/5

        public ActionResult Edit(int id = 0)
        {
            DiaDanh diadanh = db.DiaDanhs.Find(id);
            if (diadanh == null)
            {
                return HttpNotFound();
            }
            return View(diadanh);
        }

        //
        // POST: /DiaDanh/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(DiaDanh diadanh)
        {
            if (ModelState.IsValid)
            {
                diadanh.DateCreate = DateTime.Now;
                db.Entry(diadanh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(diadanh);
        }

        //
        // GET: /DiaDanh/Delete/5

        public ActionResult Delete(int id = 0)
        {
            DiaDanh diadanh = db.DiaDanhs.Find(id);
            if (diadanh == null)
            {
                return HttpNotFound();
            }
            return View(diadanh);
        }

        //
        // POST: /DiaDanh/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DiaDanh diadanh = db.DiaDanhs.Find(id);
            db.DiaDanhs.Remove(diadanh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project-LTW/Project-LTW/Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project_LTW.Models;

namespace Project_LTW.Controllers
{
    public class RatingController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Rating/

        public ActionResult Index()
        {
            var ratings = db.Ratings.Include(r => r.DiaDanhs);
            return View(ratings.ToList());
        }

        //
        // GET: /Rating/Details/5

        public ActionResult Details(int id = 0)
        {
            Rating rating = db.Ratings.Find(id);
            if (rating == null)
            {
                return HttpNotFound();
            }
            return View(rating);
        }

        //
        // GET: /Rating/Create

        public ActionResult Create()
        {
            ViewBag.TrungTamID = new SelectList(db.TrungTam, "ID", "Title");
            ViewBag.DiaDanhID = new SelectList(db.DiaDanhs, "ID", "Title");
            return View();
        }

        //
        // POST: /Rating/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Rating rating,int iddiadanh)
        {
            if (ModelState.IsValid)
            {
                rating.DiaDanhID = iddiadanh;
                db.Ratings.Add(rating);
                db.SaveChanges();
                return RedirectToAction("Details/" + iddiadanh, "DiaDanh");
                //return RedirectToAction("Index");
            }

            ViewBag.DiaDanhID = new SelectList(db.DiaDanhs, "ID", "Title", rating.DiaDanhID);
            return View(rating);
        }

        //
        // GET: /Rating/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Rating rating = db.Ratings.Find(id);
            if (rating == null)
            {
                return HttpNotFound();
            }
            ViewBag.DiaDanhID = new SelectList(db.DiaDanhs, "ID", "Title", rating.DiaDanhID);
            return View(rating);
        }

        //
        // POST: /Rating/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Rating rating)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rating).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DiaDanhID = new SelectList(db.DiaDanhs, "ID", "Title", rating.DiaDanhID);
            return View(rating);
        }

        //
        // GET: /Rating/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Rating rating = db.Ratings.Find(id);
            if (rating == null)
            {
                return HttpNotFound();
            }
            return View(rating);
        }

        //
        // POST: /Rating/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rating rating = db.Ratings.Find(id);
            db.Ratings.Remove(rating);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project-LTW/Project-LTW/Views/DiaDanh/Create.cshtml
@model Project_LTW.Models.DiaDanh

@{
    ViewBag.Title = "InfoTourism - Nơi tìm kiếm và chia sẻ thông tin du lịch";
    }
<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>DiaDanh</legend>

        <div class="editor-label">
            <h3>Tên Bài Viết</h3>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            <h3>Nội Dung Bài Viết</h3>
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body, new { @id="ckeContent"})
            <script type="text/javascript">
                CKEDITOR.replace("ckeContent")
            </script>
        </div>

        @*<div class="editor-label">
            @Html.LabelFor(model => model.DateCreate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateCreate)
            @Html.ValidationMessageFor(model => model.DateCreate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DanhGiaDD)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DanhGiaDD)
            @Html.ValidationMessageFor(model => model.DanhGiaDD)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserProfileID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserProfileID)
            @Html.ValidationMessageFor(model => model.UserProfileID)
        </div>*@
        <div class="editor-label">
            <h3>Tag</h3> <i>(Thêm các mô tả cho bài viết)</i>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => new Project_LTW.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new Project_LTW.Models.Tag().Content)
        </div>
        <p>
            <input type="submit" value="Đăng Bài" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project-LTW/Project-LTW/Views/DiaDanh/Delete.cshtml
@model Project_LTW.Models.DiaDanh

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>DiaDanh</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.Raw(Model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfileID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfileID)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Project-LTW/Project-LTW/Views/DiaDanh/Details.cshtml
@model Project_LTW.Models.DiaDanh

@{
    ViewBag.Title = "InfoTourism - Nơi tìm kiếm và chia sẻ thông tin du lịch";
}

<h2>Địa Danh Du Lịch</h2>

<fieldset>
    <legend>DiaDanh</legend>

    <div class="display-field">
        <h4>@Html.DisplayFor(model => model.Title)</h4>
    </div>
    @foreach (var rate in Model.Ratings.OrderByDescending(x=>x.Diem).Take(1))
    {
        <div class="display-field">
            <i>Đánh giá: @Html.DisplayFor(model => rate.Diem)</i>
        </div>
    }
    Đăng ngày: @Html.DisplayFor(model => model.DateCreate) bởi @Html.DisplayFor(model => model.UserProfile.UserName)
    <div class="display-label">
         <h3>Nội Dung</h3>
    </div>
    <div class="display-field">
       @Html.Raw(Model.Body)
    </div>

    @*<div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfileID)
    </div>*@
</fieldset>

<fieldset>
    <legend>Tag</legend>
    <div class="display-label">
        <h3>Tag:</h3>
    </div>
    @foreach (var tag in Model.Tags)
    {
        <div class="display-field">
           <i> @Html.ActionLink(tag.Content.ToString(), "Details", new { Controller = "Tag", action = "Details", id = tag.ID })</i>
        </div>
    }
</fieldset>
@Html.Partial("_addRating",new Project_LTW.Models.Rating(),ViewData)
@Html.Partial("_addComment", new Project_LTW.Models.Comment(), ViewData)
<fieldset>
    <legend>Comment</legend>
    <div class="display-field">
        <h3>Comment:</h3>
    </div>
    <div id="result">
        @foreach (var comment in Model.Comments.OrderByDescending(x => x.DateCreated).Take(10))
        {
            if(comment.Loai==1)
            {
                <div class="display-field">
               <h5>Tác giả: @Html.DisplayFor(x => comment.Author)</h5>
            </div>
            <div class="display-field">
               Cách đây: @Html.DisplayFor(x => comment.LastTime) phút
            </div>
            <div class="display-field">
                @Html.DisplayFor(x => comment.Body)
            </div> 
            }
            
        }
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Lên Đầu Trang","Details",new {id=Model.ID})
</p>

Project-LTW/Project-LTW/Views/DiaDanh/Edit.cshtml
@model Project_LTW.Models.DiaDanh

@{
    ViewBag.Title = "InfoTourism - Nơi tìm kiếm và chia sẻ thông tin du lịch";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>DiaDanh</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            <h3>Tiêu Đề</h3>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <div class="editor-label">
            <h3>Nội Dung</h3>
        </div>
        @Html.TextAreaFor(model => model.Body, new { @id = "ckeContent" })
            <script type="text/javascript">
                CKEDITOR.replace("ckeContent")
            </script>
        @*<div class="editor-label">
            @Html.LabelFor(model => model.DateCreate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateCreate)
            @Html.ValidationMessageFor(model => model.DateCreate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserProfileID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserProfileID)
            @Html.ValidationMessageFor(model => model.UserProfileID)
        </div>*@

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project-LTW/Project-LTW/Views/DiaDanh/Index.cshtml
@model IEnumerable<Project_LTW.Models.DiaDanh>

@{
    ViewBag.Title = "InfoTourism - Nơi tìm kiếm và chia sẻ thông tin du lịch";

}
@using (Html.BeginForm("Index", "DiaDanh", FormMethod.Get))
{
    <p>
        @*Publisher: @Html.DropDownList("Publishers", "All")*@
        Tên bài viết: @Html.TextBox("strSearch")
        <input type="submit" value="Search" />
    </p>
} 
<h2>Địa Danh Du Lịch</h2>

<p>
    @Html.ActionLink("Đăng Bài Mới", "Create")
</p>
<style>
    table, th, td {
        border: 2px solid #31fb0a;
        border-collapse: collapse;
    }
</style>
<table>
    <tr>
        <th width="192">Tiêu đề</th>
        <th width="750">Nội dung</th>
        <th width="130">Ngày đăng</th>
        <th width="140">Thao tác</th>

    </tr>
    @foreach (var item in Model.OrderByDescending(x => x.DateCreate))
    {
        <tr>
            <td>@Html.ActionLink(item.Title, "Details", new { id = item.ID })</td>
            <td>@Html.Raw(item.Body)</td>
            <td>@item.DateCreate</td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ID })
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
            </td>

        </tr>
    }

</table>

Project-LTW/Project-LTW/Views/DiaDanh/_addComment.cshtml
@model Project_LTW.Models.Comment

@using (Html.BeginForm("Create", "Comment", FormMethod.Post, new { id = "My-Form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>
        <div class="display-label">
            <h4>Bình Luận</h4>
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div>
            @Html.Hidden("idtrungtam", ViewData["idtrungtam"])
            @Html.Hidden("iddiadanh", ViewData["iddiadanh"])
            @Html.Hidden("Loai", ViewData["Loai"])
            <p>
                <input type="submit" value="Bình luận" />
            </p>
        </div>
    </fieldset>
}

<script src="~/Scripts/addComment.js"></script>

Project-LTW/Project-LTW/Views/DiaDanh/_addRating.cshtml
@model Project_LTW.Models.Rating

@using (Html.BeginForm("Create", "Rating", new { iddiadanh = ViewData["iddiadanh"] }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Rating</legend>

        <div class="editor-label">
            <h4>Đánh Giá</h4>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Diem)
            @Html.ValidationMessageFor(model => model.Diem)
        </div>

        <p>
            <input type="submit" value="Đánh giá" />
        </p>
    </fieldset>
}